/** @type {Array<{ id: string; name: string; description: string; tailwindPreview: string; export: Record<string, unknown> }>} */
export const TEMPLATES = [
  {
    id: 'modern',
    name: 'Modern',
    description: 'Deep glass, cool contrast, soft frame glow',
    tailwindPreview: 'from-slate-900 via-slate-800 to-slate-900',
    export: {
      kind: 'modern',
      padding: 44,
      gap: 18,
      cornerRadius: 22,
      frameInset: 3,
      frameOpacity: 0.35,
      captionColor: '#f8fafc',
      captionFont: '600 28px ui-sans-serif, system-ui, sans-serif',
      dateFont: '500 18px ui-sans-serif, system-ui, sans-serif',
      dateColor: 'rgba(248,250,252,0.72)',
      gradient: {
        type: 'linear',
        angle: 135,
        stops: [
          [0, '#0f172a'],
          [0.5, '#1e293b'],
          [1, '#0f172a'],
        ],
      },
    },
  },
  {
    id: 'minimalist',
    name: 'Minimalist',
    description: 'Paper-white canvas, hairline borders',
    tailwindPreview: 'from-zinc-50 via-white to-zinc-100',
    export: {
      kind: 'minimal',
      padding: 48,
      gap: 20,
      cornerRadius: 16,
      frameInset: 2,
      frameOpacity: 0.85,
      captionColor: '#0f172a',
      captionFont: '600 26px ui-sans-serif, system-ui, sans-serif',
      dateFont: '500 17px ui-sans-serif, system-ui, sans-serif',
      dateColor: 'rgba(15,23,42,0.55)',
      gradient: {
        type: 'linear',
        angle: 180,
        stops: [
          [0, '#fafafa'],
          [1, '#f4f4f5'],
        ],
      },
    },
  },
  {
    id: 'pastel',
    name: 'Pastel',
    description: 'Soft candy gradients & airy frames',
    tailwindPreview: 'from-pink-200 via-violet-100 to-sky-200',
    export: {
      kind: 'pastel',
      padding: 42,
      gap: 16,
      cornerRadius: 28,
      frameInset: 0,
      frameOpacity: 0.25,
      captionColor: '#4c1d95',
      captionFont: '700 26px ui-sans-serif, system-ui, sans-serif',
      dateFont: '600 17px ui-sans-serif, system-ui, sans-serif',
      dateColor: 'rgba(76,29,149,0.6)',
      gradient: {
        type: 'linear',
        angle: 160,
        stops: [
          [0, '#fbcfe8'],
          [0.45, '#ddd6fe'],
          [1, '#bae6fd'],
        ],
      },
    },
  },
  {
    id: 'vintage',
    name: 'Vintage',
    description: 'Warm film tones & parchment texture',
    tailwindPreview: 'from-amber-900 via-amber-800 to-stone-900',
    export: {
      kind: 'vintage',
      padding: 46,
      gap: 18,
      cornerRadius: 12,
      frameInset: 4,
      frameOpacity: 0.5,
      captionColor: '#fef3c7',
      captionFont: '700 26px Georgia, serif',
      dateFont: '500 18px Georgia, serif',
      dateColor: 'rgba(254,243,199,0.62)',
      gradient: {
        type: 'linear',
        angle: 145,
        stops: [
          [0, '#422006'],
          [0.4, '#713f12'],
          [1, '#1c1917'],
        ],
      },
    },
  },
  {
    id: 'aesthetic',
    name: 'Aesthetic',
    description: 'Moody purple haze & glow frames',
    tailwindPreview: 'from-fuchsia-950 via-violet-950 to-indigo-950',
    export: {
      kind: 'aesthetic',
      padding: 40,
      gap: 20,
      cornerRadius: 26,
      frameInset: 2,
      frameOpacity: 0.4,
      captionColor: '#fdf4ff',
      captionFont: '600 28px ui-sans-serif, system-ui, sans-serif',
      dateFont: '500 18px ui-sans-serif, system-ui, sans-serif',
      dateColor: 'rgba(253,244,255,0.65)',
      gradient: {
        type: 'linear',
        angle: 125,
        stops: [
          [0, '#4a044e'],
          [0.5, '#312e81'],
          [1, '#0f172a'],
        ],
      },
      glow: true,
    },
  },
  {
    id: 'solace',
    name: 'Solace',
    description: 'Misty blue-gray calm, soft silver frames',
    tailwindPreview: 'from-slate-200 via-slate-100 to-zinc-200',
    export: {
      kind: 'solace',
      padding: 44,
      gap: 16,
      cornerRadius: 20,
      frameInset: 2,
      frameOpacity: 0.3,
      captionColor: '#1e293b',
      captionFont: '600 28px ui-sans-serif, system-ui, sans-serif',
      dateFont: '500 18px ui-sans-serif, system-ui, sans-serif',
      dateColor: 'rgba(30,41,59,0.55)',
      gradient: {
        type: 'linear',
        angle: 165,
        stops: [
          [0, '#e2e8f0'],
          [0.45, '#f1f5f9'],
          [1, '#cbd5e1'],
        ],
      },
    },
  },
  {
    id: 'champagne',
    name: 'Champagne',
    description: 'Ivory & gold sparkle for celebrations',
    tailwindPreview: 'from-amber-100 via-yellow-50 to-orange-100',
    export: {
      kind: 'champagne',
      padding: 46,
      gap: 18,
      cornerRadius: 18,
      frameInset: 3,
      frameOpacity: 0.4,
      captionColor: '#713f12',
      captionFont: '600 28px ui-sans-serif, system-ui, sans-serif',
      dateFont: '500 18px ui-sans-serif, system-ui, sans-serif',
      dateColor: 'rgba(113,63,18,0.55)',
      gradient: {
        type: 'linear',
        angle: 140,
        stops: [
          [0, '#fef3c7'],
          [0.5, '#fffbeb'],
          [1, '#fde68a'],
        ],
      },
    },
  },
  {
    id: 'forest',
    name: 'Forest',
    description: 'Deep evergreen with mint highlights',
    tailwindPreview: 'from-emerald-950 via-green-900 to-teal-950',
    export: {
      kind: 'forest',
      padding: 42,
      gap: 16,
      cornerRadius: 20,
      frameInset: 2,
      frameOpacity: 0.35,
      captionColor: '#ecfdf5',
      captionFont: '600 28px ui-sans-serif, system-ui, sans-serif',
      dateFont: '500 18px ui-sans-serif, system-ui, sans-serif',
      dateColor: 'rgba(236,253,245,0.65)',
      gradient: {
        type: 'linear',
        angle: 150,
        stops: [
          [0, '#022c22'],
          [0.5, '#14532d'],
          [1, '#134e4a'],
        ],
      },
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    description: 'Coastal blues with sea-glass mood',
    tailwindPreview: 'from-sky-950 via-cyan-900 to-blue-950',
    export: {
      kind: 'ocean',
      padding: 40,
      gap: 18,
      cornerRadius: 24,
      frameInset: 2,
      frameOpacity: 0.32,
      captionColor: '#e0f2fe',
      captionFont: '600 28px ui-sans-serif, system-ui, sans-serif',
      dateFont: '500 18px ui-sans-serif, system-ui, sans-serif',
      dateColor: 'rgba(224,242,254,0.65)',
      gradient: {
        type: 'linear',
        angle: 135,
        stops: [
          [0, '#0c4a6e'],
          [0.45, '#164e63'],
          [1, '#1e3a5f'],
        ],
      },
    },
  },
  {
    id: 'sakura',
    name: 'Sakura',
    description: 'Cherry blossom blush & soft paper',
    tailwindPreview: 'from-pink-50 via-rose-100 to-fuchsia-50',
    export: {
      kind: 'sakura',
      padding: 44,
      gap: 14,
      cornerRadius: 26,
      frameInset: 1,
      frameOpacity: 0.28,
      captionColor: '#9d174d',
      captionFont: '600 28px ui-sans-serif, system-ui, sans-serif',
      dateFont: '500 18px ui-sans-serif, system-ui, sans-serif',
      dateColor: 'rgba(157,23,77,0.55)',
      gradient: {
        type: 'linear',
        angle: 175,
        stops: [
          [0, '#fce7f3'],
          [0.5, '#fdf2f8'],
          [1, '#fbcfe8'],
        ],
      },
    },
  },
  {
    id: 'midnight',
    name: 'Midnight',
    description: 'Pure black velvet with silver trim',
    tailwindPreview: 'from-zinc-950 via-neutral-950 to-black',
    export: {
      kind: 'midnight',
      padding: 48,
      gap: 20,
      cornerRadius: 14,
      frameInset: 2,
      frameOpacity: 0.55,
      captionColor: '#fafafa',
      captionFont: '600 26px ui-sans-serif, system-ui, sans-serif',
      dateFont: '500 17px ui-sans-serif, system-ui, sans-serif',
      dateColor: 'rgba(250,250,250,0.55)',
      gradient: {
        type: 'linear',
        angle: 145,
        stops: [
          [0, '#171717'],
          [0.5, '#0a0a0a'],
          [1, '#262626'],
        ],
      },
    },
  },
]

export function getTemplateById(id) {
  return TEMPLATES.find((t) => t.id === id) ?? TEMPLATES[0]
}
